### ISSUE TITLE
RefreshValues does not return any error when node is dead.

### ISSUE THREAD

**Issue by spudwebb** [zwave-js/ZWaveJS.NET#52] opened 2023-11-14 19:37 UTC
If the following code is called for a dead node
`CMDResult result = await node.RefreshValues();`
the `result.Success` value is always true

other methods like `SetValue()` correctly return false for `result.Success` with a message saying "The message cannot be sent because node 53 is dead (ZW0202)"

Looks like the problem is probably more in ZWave JS Server or node-zwave-js, but I wanted to check here first to know what you think.

**Comment by marcus-j-davies** [comment] 2023-11-14 20:30
Hi @spudwebb 

That is Driver side.
@AlCalzone, is that by design? as it would make sense to fail on Refresh for a dead node?

**Comment by AlCalzone** [comment] 2023-11-14 20:43
The driver doesn't return anything, but it also doesn't throw an error. I didn't want to fail the whole method when just a single query failed.
The server also doesn't return a success value:
https://github.com/zwave-js/zwave-js-server/blob/03405c02304c4555900c4fe1a5e7a873becfd11e/src/lib/node/message_handler.ts#L116C1-L119

**Comment by marcus-j-davies** [comment] 2023-11-14 20:50
> The server also doesn't return a success value:

It does by default, if no exception occurred 😅 
every call yields a `success` property, which denotes if an error occurred driver/server side, so that will make sense, given nothing is going wrong

**Comment by AlCalzone** [comment] 2023-11-14 20:55
I see, that was hidden somewhere else. I guess it could be an enhancement to collect the errors while querying and return them to be able to indicate that something went wrong.

**Comment by marcus-j-davies** [comment] 2023-11-17 21:31
@AlCalzone,
Do you want to transfer this as a future enhancement?, not sure I can add much here, I don't have the right to transfer issues 🤷

**Comment by marcus-j-davies** [comment] 2023-11-19 18:50
I'll close this as an upstream enhancement.

**Closed by marcus-j-davies** 2023-11-19 18:50 UTC
Labels: upstream
